const {
  blackA,
  whiteA,
  tomato,
  tomatoDark,
  red,
  redDark,
  crimson,
  crimsonDark,
  pink,
  pinkDark,
  plum,
  plumDark,
  purple,
  purpleDark,
  violet,
  violetDark,
  indigo,
  indigoDark,
  blue,
  blueDarkA,
  cyan,
  cyanDark,
  teal,
  tealDark,
  green,
  greenDark,
  grass,
  grassDark,
  orange,
  orangeDark,
  brown,
  brownDark,
  sky,
  skyDark,
  mint,
  mintDark,
  lime,
  limeDark,
  yellow,
  yellowDark,
  amberA,
  amberDark,
  gray,
  grayDark,
  mauve,
  mauveDark,
  slate,
  slateDark,
  sage,
  sageDark,
  olive,
  oliveDark,
  sand,
  sandDark,
  gold,
  goldDark,
  bronze,
  bronzeDark,
} = require('@radix-ui/colors');

const colors = {
  transparent: 'transparent',
  current: 'currentColor',

  primaryBase: violet.violet1,
  primaryBgSubtle: violet.violet2,
  primaryBg: violet.violet3,
  primaryBgHover: violet.violet4,
  primaryBgActive: violet.violet5,
  primaryLine: violet.violet6,
  primaryBorder: violet.violet7,
  primaryBorderHover: violet.violet8,
  primaryFocusRing: violet.violet8,
  primarySolid: violet.violet9,
  primarySolidHover: violet.violet10,
  primaryText: violet.violet11,
  primaryTextContrast: violet.violet12,

  successBase: green.green1,
  successBgSubtle: green.green2,
  successBg: green.green3,
  successBgHover: green.green4,
  successBgActive: green.green5,
  successLine: green.green6,
  successBorder: green.green7,
  successBorderHover: green.green8,
  successSolid: green.green9,
  successSolidHover: green.green10,
  successText: green.green11,
  successTextContrast: green.green12,

  warningBase: yellow.yellow1,
  warningBgSubtle: yellow.yellow2,
  warningBg: yellow.yellow3,
  warningBgHover: yellow.yellow4,
  warningBgActive: yellow.yellow5,
  warningLine: yellow.yellow6,
  warningBorder: yellow.yellow7,
  warningBorderHover: yellow.yellow8,
  warningSolid: yellow.yellow9,
  warningSolidHover: yellow.yellow10,
  warningText: yellow.yellow11,
  warningTextContrast: yellow.yellow12,
  
  errorBase: red.red1,
  errorBgSubtle: red.red2,
  errorBg: red.red3,
  errorBgHover: red.red4,
  errorBgActive: red.red5,
  errorLine: red.red6,
  errorBorder: red.red7,
  errorBorderHover: red.red8,
  errorSolid: red.red9,
  errorSolidHover: red.red10,
  errorText: red.red11,
  errorTextContrast: red.red12,

  mauveBase: mauve.mauve1,
  mauveBgSubtle: mauve.mauve2,
  mauveBg: mauve.mauve3,
  mauveBgHover: mauve.mauve4,
  mauveBgActive: mauve.mauve5,
  mauveLine: mauve.mauve6,
  mauveBorder: mauve.mauve7,
  mauveBorderHover: mauve.mauve8,
  mauveSolid: mauve.mauve9,
  mauvePlaceholderText: mauve.mauve9,
  mauveSolidHover: mauve.mauve10,
  mauveText: mauve.mauve11,
  mauveTextContrast: mauve.mauve12,

  ...blackA,
  ...whiteA,
  ...tomato,
  ...tomatoDark,
  ...red,
  ...redDark,
  ...crimson,
  ...crimsonDark,
  ...pink,
  ...pinkDark,
  ...plum,
  ...plumDark,
  ...purple,
  ...purpleDark,
  ...violet,
  ...violetDark,
  ...indigo,
  ...indigoDark,
  ...blue,
  ...blueDarkA,
  ...cyan,
  ...cyanDark,
  ...teal,
  ...tealDark,
  ...green,
  ...greenDark,
  ...grass,
  ...grassDark,
  ...orange,
  ...orangeDark,
  ...brown,
  ...brownDark,
  ...sky,
  ...skyDark,
  ...mint,
  ...mintDark,
  ...lime,
  ...limeDark,
  ...yellow,
  ...yellowDark,
  ...amberA,
  ...amberDark,
  ...gray,
  ...grayDark,
  ...mauve,
  ...mauveDark,
  ...slate,
  ...slateDark,
  ...sage,
  ...sageDark,
  ...olive,
  ...oliveDark,
  ...sand,
  ...sandDark,
  ...gold,
  ...goldDark,
  ...bronze,
  ...bronzeDark,
};

module.exports = colors;
