const { fontFamily } = require('tailwindcss/defaultTheme');
const {
  blackA,
  whiteA,
  tomato,
  tomatoDark,
  red,
  redDark,
  crimson,
  crimsonDark,
  pink,
  pinkDark,
  plum,
  plumDark,
  purple,
  purpleDark,
  violet,
  violetDark,
  indigo,
  indigoDark,
  blue,
  blueDarkA,
  cyan,
  cyanDark,
  teal,
  tealDark,
  green,
  greenDark,
  grass,
  grassDark,
  orange,
  orangeDark,
  brown,
  brownDark,
  sky,
  skyDark,
  mint,
  mintDark,
  lime,
  limeDark,
  yellow,
  yellowDark,
  amberA,
  amberDark,
  gray,
  grayDark,
  mauve,
  mauveDark,
  slate,
  slateDark,
  sage,
  sageDark,
  olive,
  oliveDark,
  sand,
  sandDark,
  gold,
  goldDark,
  bronze,
  bronzeDark,
} = require('@radix-ui/colors');

/** @type {import('tailwindcss').Config} */
const config = {
  content: ['./src/**/*.{ts,tsx}'],
  theme: {
    colors: {
      transparent: 'transparent',
      current: 'currentColor',
      ...blackA,
      ...whiteA,
      ...tomato,
      ...tomatoDark,
      ...red,
      ...redDark,
      ...crimson,
      ...crimsonDark,
      ...pink,
      ...pinkDark,
      ...plum,
      ...plumDark,
      ...purple,
      ...purpleDark,
      ...violet,
      ...violetDark,
      ...indigo,
      ...indigoDark,
      ...blue,
      ...blueDarkA,
      ...cyan,
      ...cyanDark,
      ...teal,
      ...tealDark,
      ...green,
      ...greenDark,
      ...grass,
      ...grassDark,
      ...orange,
      ...orangeDark,
      ...brown,
      ...brownDark,
      ...sky,
      ...skyDark,
      ...mint,
      ...mintDark,
      ...lime,
      ...limeDark,
      ...yellow,
      ...yellowDark,
      ...amberA,
      ...amberDark,
      ...gray,
      ...grayDark,
      ...mauve,
      ...mauveDark,
      ...slate,
      ...slateDark,
      ...sage,
      ...sageDark,
      ...olive,
      ...oliveDark,
      ...sand,
      ...sandDark,
      ...gold,
      ...goldDark,
      ...bronze,
      ...bronzeDark,
    },
    extend: {
      fontFamily: {
        sans: ['var(--font-sans)', ...fontFamily.sans]
      }
    },
  },
  plugins: [],
};

module.exports = config;
